-- Customer Segmentation using RFM Analysis (SQL Project)

-- ============================================================
--  OVERVIEW
-- ============================================================
-- This project performs RFM (Recency, Frequency, Monetary) analysis using SQL 
-- to segment customers based on purchasing behavior.

-- ============================================================
-- OBJECTIVES
-- ============================================================
-- 1. Identify high-value and loyal customers
-- 2. Detect at-risk and churn-prone customers
-- 3. Analyze customer purchasing patterns
-- 4. Generate actionable business insights for retention and growth

-- ============================================================
--  WHAT IS RFM ANALYSIS?
-- ============================================================
-- Recency   → How recently a customer made a purchase
-- Frequency → How often a customer makes purchases
-- Monetary  → How much money a customer spends



-- ============================================================
--  DATA CLEANING & PREPARATION
-- ============================================================




DROP TABLE IF EXISTS CUSTOMER_DATA;

--CREATE A TABLE TO STORE CUSTOMER INFORMATION
CREATE TABLE CUSTOMER_DATA(
			CUSTOMER_ID VARCHAR(100),
			CUSTOMER_UNIQUE_ID VARCHAR(100),
			CUSTOMER_ZIP_CODE INT,
			CUSTOMER_CITY VARCHAR(200),
			CUSTOMER_STATE VARCHAR(50)
		);
--CHECKING FOR NULL VALUES.
SELECT COUNT(CUSTOMER_ID),COUNT(CUSTOMER_UNIQUE_ID),
COUNT(CUSTOMER_ZIP_CODE),COUNT(CUSTOMER_CITY),
COUNT(CUSTOMER_STATE) FROM CUSTOMER_DATA;
--NOTE:-NO NULL_VALUES

---CHECKING FOR DUPLICATE VALUES

WITH DUPLICATE_CHECK_1 AS (
						 SELECT *,
						 ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID,CUSTOMER_UNIQUE_ID,CUSTOMER_ZIP_CODE,
						 CUSTOMER_CITY,CUSTOMER_STATE ORDER BY CUSTOMER_ID ) AS RNK
						 FROM CUSTOMER_DATA
						 
)
SELECT * FROM DUPLICATE_CHECK_1
WHERE RNK>1;

SELECT * FROM CUSTOMER_DATA;
--NOTE:-NO DUPLICATE ROWS AVAILABLE IN THE TABLE
-------------------------------------------------------------------
-------------------------------------------------------------------
--CREATE A TABLE TO STORE THE GEOLOCATION


DROP TABLE IF EXISTS GEOLOCATION;

CREATE TABLE GEOLOCATION(
		     GEO_ZIP_CODE INT,
			 GEO_LATITUDE DECIMAL(8,6),
			 GEO_LONGITUDE DECIMAL(9,6),
			 GEO_CITY VARCHAR(200),
			 GEO_STATE VARCHAR(50)
			 );

--CHECKING FOR NULL VALUES
SELECT COUNT(GEO_ZIP_CODE),COUNT(GEO_LATITUDE),COUNT(GEO_LONGITUDE),
COUNT(GEO_CITY),COUNT(GEO_STATE) FROM GEOLOCATION;
--NOTE:- NO NULL VALUES

--CHECKING FOR DUPLICATE

WITH DUPLICATE_CHECK_2 AS (
							SELECT * ,
							ROW_NUMBER() OVER (PARTITION BY GEO_ZIP_CODE,GEO_LATITUDE,GEO_LONGITUDE,
							GEO_CITY,GEO_STATE ORDER BY GEO_ZIP_CODE)AS RNK
							FROM GEOLOCATION
)
SELECT * FROM DUPLICATE_CHECK_2
WHERE RNK > 1;
--NOTE:- THERE ARE MULTIPLE DUPLICATE ROWS IN THE DATA SET


--DELETING DUPLICATE ROWS
DELETE FROM GEOLOCATION
WHERE CTID IN
(SELECT CTID
	FROM(SELECT CTID,
			ROW_NUMBER() OVER (PARTITION BY GEO_ZIP_CODE,GEO_LATITUDE,GEO_LONGITUDE,
							GEO_CITY,GEO_STATE ORDER BY CTID)AS RNK
							FROM GEOLOCATION
		)t
	WHERE RNK>1
	);

--NOTE:- 1000 ROWS OF DUPLICATE DATA SUCCESSFULLY DELETED
----------------------------------------------------------------------
----------------------------------------------------------------------

--CREATE A TABLE ORDER_LIST

DROP TABLE IF EXISTS ORDER_LIST;

CREATE TABLE ORDER_LIST(
			ORDER_ID VARCHAR(100),
			ORDER_ITEM INT,
			PRODUCT_ID VARCHAR(100),
			SELLER_ID VARCHAR(100),
			SHIPPING_LIMIT_DATE TIMESTAMP,
			PRICE DECIMAL(10,2),
			FREIGHT_VALUE DECIMAL(10,2)
			
);

--CHECKING FOR NULL_VALUES

SELECT COUNT(ORDER_ID),COUNT(ORDER_ITEM),COUNT(PRODUCT_ID),
COUNT(SELLER_ID),COUNT(SHIPPING_LIMIT_DATE),COUNT(PRICE),
COUNT(FREIGHT_VALUE) FROM ORDER_LIST;
--NOTE:- NO NULL VALUES PRESENT

--CHECKING FOR DUPLICATE VALUES

WITH DUPLICATE_CHECK_3 AS (
							SELECT *,
							ROW_NUMBER() OVER (PARTITION BY ORDER_ID,ORDER_ITEM,PRODUCT_ID,
											   SELLER_ID,SHIPPING_LIMIT_DATE,PRICE,FREIGHT_VALUE
											   ORDER BY ORDER_ID)AS RNK
							FROM ORDER_LIST
)
SELECT * 
FROM DUPLICATE_CHECK_3
WHERE
RNK>1;

--NOTE:- NO DUPLICATE ROWS DETECTED
--------------------------------------------------------------------
--------------------------------------------------------------------


--CREATE TABLE PAYMENT_DETAIL
DROP TABLE IF EXISTS PAYMENT_DETAIL;

CREATE TABLE PAYMENT_DETAIL(
			ORDER_ID VARCHAR(100),
			PAYMENT_SEQUENCE INT,
			PAYMENT_TYPE VARCHAR(50),
			INSTALLMENT INT,
			PAYMENT_VALUE DECIMAL(10,2)
);

--CHECKING FOR NULL VALUES

SELECT COUNT(ORDER_ID),COUNT(PAYMENT_SEQUENCE),COUNT(PAYMENT_TYPE),
COUNT(INSTALLMENT),COUNT(PAYMENT_VALUE) FROM PAYMENT_DETAIL;

--NOTE:- NO NULL VALUES PRESENT

--CHECKING FOR DUPLICATE VALUES
WITH DUPLICATE_CHECK_4 AS (
							SELECT *,
							ROW_NUMBER() OVER (PARTITION BY ORDER_ID,PAYMENT_SEQUENCE,PAYMENT_TYPE,
											  INSTALLMENT,PAYMENT_VALUE ORDER BY ORDER_ID)
											  AS RNK
							FROM PAYMENT_DETAIL
)
SELECT * FROM DUPLICATE_CHECK_4
WHERE RNK>1;

--NOTE:- THERE ARE NO NULL ROWS PRESENT IN THE TABLE
--------------------------------------------------------------------
--------------------------------------------------------------------

--CREATE TABLE ORDER_REVIEW
DROP TABLE IF EXISTS ORDER_REVIEW;

CREATE TABLE ORDER_REVIEW(
			 REVIEW_ID VARCHAR(100),
			 ORDER_ID VARCHAR(100),
			 REVIEW_SCORE INT,
			 REVIEW_COMMENT_TITLE VARCHAR(100),
			 REVIEW_COMMENT_MESSAGE VARCHAR(500),
			 REVIEW_CREATION_DATE TIMESTAMP,
			 REVIEW_ANSWER_DATE TIMESTAMP
 );

SELECT * FROM ORDER_REVIEW;
--CHECKING FOR NULL VALUES
SELECT COUNT(REVIEW_ID),COUNT(ORDER_ID),COUNT(REVIEW_SCORE),
COUNT(REVIEW_COMMENT_TITLE),COUNT(REVIEW_COMMENT_MESSAGE),COUNT(REVIEW_CREATION_DATE),
COUNT(REVIEW_ANSWER_DATE) FROM ORDER_REVIEW;

--UPDATING NULL_CELLS
UPDATE ORDER_REVIEW
SET
REVIEW_COMMENT_TITLE=COALESCE(REVIEW_COMMENT_TITLE,'NOT AVAILABLE'),
REVIEW_COMMENT_MESSAGE=COALESCE(REVIEW_COMMENT_MESSAGE,'NOT AVAILABLE');

--CHECKING FOR DUPLICATE VALUES

WITH DUPLICATE_CHECK_5 AS (
						   SELECT *,
						   ROW_NUMBER() OVER (PARTITION BY REVIEW_ID,ORDER_ID,REVIEW_SCORE,
						   					 REVIEW_COMMENT_TITLE,REVIEW_COMMENT_MESSAGE,
											 REVIEW_CREATION_DATE,REVIEW_ANSWER_DATE ORDER BY
											 REVIEW_ID) AS RNK
							FROM ORDER_REVIEW
)
SELECT * FROM DUPLICATE_CHECK_5
WHERE RNK > 1;

--NOTE:-THERE ARE NO DUPLICATE ROWS IN THE TABLE
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------


---CREATE TABLE ORDER INFO
DROP TABLE IF EXISTS ORDER_INFO;

CREATE TABLE ORDER_INFO(
			 ORDER_ID VARCHAR (100),
			 CUSTOMER_ID VARCHAR(100),
			 ORDER_STATUS VARCHAR(50),
			 PURCHASE_DATE TIMESTAMP,
			 APPROVED_DATE TIMESTAMP,
			 SHIPPING_DATE TIMESTAMP,
			 DELIVERY_DATE TIMESTAMP,
			 ESTIMATED_DELIVERY_DATE TIMESTAMP
			 
);

---CHECKING FOR NULL VALUES
SELECT COUNT(ORDER_ID),COUNT(CUSTOMER_ID),COUNT(ORDER_STATUS),
COUNT(PURCHASE_DATE),COUNT(APPROVED_DATE),COUNT(SHIPPING_DATE),
COUNT(DELIVERY_DATE),COUNT(ESTIMATED_DELIVERY_DATE) FROM ORDER_INFO;

--NOTE:- MULTIPLE COLUMNS HAVE NULL VALUES SO MUST CHECK FOR PERCENTAGE OF NUL VALUES

--CHECKING FOR NULL_PERCENT
SELECT
ROUND(COUNT(*) FILTER (WHERE ORDER_ID IS NULL)*100/COUNT(*),2) AS ORDER_PERCENT,
ROUND(COUNT(*) FILTER (WHERE CUSTOMER_ID IS NULL)*100/COUNT(*),2) AS CUSTOMER_PERCENT,
ROUND(COUNT(*) FILTER (WHERE ORDER_STATUS IS NULL)*100/COUNT(*),2) AS STATUS_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PURCHASE_DATE IS NULL)*100/COUNT(*),2) AS PURCHASE_PERCENT,
ROUND(COUNT(*) FILTER (WHERE APPROVED_DATE IS NULL)*100/COUNT(*),2) AS APPROVED_PERCENT,
ROUND(COUNT(*) FILTER (WHERE SHIPPING_DATE IS NULL)*100/COUNT(*),2) AS SHIPPING_PERCENT,
ROUND(COUNT(*) FILTER (WHERE DELIVERY_DATE IS NULL)*100/COUNT(*),2) AS DELIVERY_PERCENT,
ROUND(COUNT(*) FILTER (WHERE ESTIMATED_DELIVERY_DATE IS NULL)*100/COUNT(*),2) AS ESTIMATED_PERCENT
FROM ORDER_INFO;
--NOTE:-SHIPPING_DATE HAS 1% NULL VALUES
--DELIVERY_DATE HAS 2% NULL VALUES
--MUST POPULATE THESE NULL VALUES WITH APPROPRIATE VALUES

SELECT * FROM ORDER_INFO
WHERE
APPROVED_DATE IS NULL
AND
ORDER_STATUS = 'canceled';


UPDATE ORDER_INFO
SET
APPROVED_DATE=PURCHASE_DATE
WHERE
APPROVED_DATE IS NULL AND ORDER_STATUS<>'canceled';
;


UPDATE ORDER_INFO
SET
SHIPPING_DATE=APPROVED_DATE
WHERE
SHIPPING_DATE IS NULL
AND
ORDER_STATUS<>'canceled'
;

UPDATE ORDER_INFO
SET
DELIVERY_DATE=ESTIMATED_DELIVERY_DATE
WHERE
DELIVERY_DATE IS NULL AND ORDER_STATUS<>'canceled';
;


SELECT * FROM ORDER_INFO;
--CHECKING FOR DUPLICATE ROWS

WITH DUPLICATE_CHECK_6 AS (
						   SELECT *,
						   ROW_NUMBER() OVER (PARTITION BY ORDER_ID,CUSTOMER_ID,ORDER_STATUS,PURCHASE_DATE,
						                      APPROVED_DATE,SHIPPING_DATE,DELIVERY_DATE,ESTIMATED_DELIVERY_DATE
											  ORDER BY ORDER_ID)AS RNK
						    FROM ORDER_INFO
											  
)
SELECT * FROM DUPLICATE_CHECK_6
WHERE RNK >1;

--NOTE:- THERE ARE NO DUPLICATE ROWS IN THE TABLE
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

--CREATE TABLE PRODUCT_DATASET
DROP TABLE IF EXISTS PRODUCT_DATASET;

CREATE TABLE PRODUCT_DATASET(
			PRODUCT_ID VARCHAR (100),
			PRODUCT_CATEGORY VARCHAR(250),
			PRODUCT_NAME_LENGTH INT,
			PRODUCT_DESCRIPTION_LENGTH INT,
			PRODUCT_PHOTO_QTY INT,
			PRODUCT_WEIGHT_QTY_in_gm INT,
			PRODUCT_LENGTH_in_cm INT,
			PRODUCT_HEIGHT_in_cm INT,
			PRODUCT_WIDTH_in_cm INT
);

SELECT * FROM PRODUCT_DATASET;


--CHECKING FOR NULL VALUES

SELECT COUNT(PRODUCT_ID),COUNT(PRODUCT_CATEGORY),
COUNT(PRODUCT_NAME_LENGTH),COUNT(PRODUCT_DESCRIPTION_LENGTH),
COUNT(PRODUCT_PHOTO_QTY),COUNT(PRODUCT_WEIGHT_QTY_in_gm),
COUNT(PRODUCT_LENGTH_in_cm),COUNT(PRODUCT_HEIGHT_in_cm),
COUNT(PRODUCT_WIDTH_in_cm)FROM PRODUCT_DATASET;
--NOTE:- MULTILPLE COLUMS HAVE NULL VALUES

--CHECKING FOR PERCENTAGE NULL VALUES

SELECT
ROUND(COUNT(*) FILTER (WHERE PRODUCT_ID IS NULL)*100/COUNT(*),2) AS PRODUCT_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_CATEGORY IS NULL)*100/COUNT(*),2) AS CATEGORY_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_NAME_LENGTH IS NULL)*100/COUNT(*),2) AS NAME_LENGTH_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_DESCRIPTION_LENGTH IS NULL)*100/COUNT(*),2) AS DESCRIPTION_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_PHOTO_QTY IS NULL)*100/COUNT(*),2) AS PHOTO_QTY_PERCENT,
ROUND(COUNT(*) FILTER (WHERE  PRODUCT_WEIGHT_QTY_in_gm IS NULL)*100/COUNT(*),2) AS WEIGHT_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_LENGTH_in_cm IS NULL)*100/COUNT(*),2) AS LENGTH_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_HEIGHT_in_cm IS NULL)*100/COUNT(*),2) AS HEIGHT_PERCENT,
ROUND(COUNT(*) FILTER (WHERE PRODUCT_WIDTH_in_cm IS NULL)*100/COUNT(*),2) AS WIDTH_PERCENT
FROM PRODUCT_DATASET;

--NOTE:- ONE PRODUCT_CATEGORY,PRODUCT_NAME_LENGTH,PRODUCT_DESCRIPTION_LENGTH,PRODUCT_PHOTO_QTY ARE NULL 

--DELETING NULL VALUES
DELETE FROM PRODUCT_DATASET
WHERE
PRODUCT_CATEGORY IS NULL
OR 
PRODUCT_NAME_LENGTH IS NULL
OR 
PRODUCT_DESCRIPTION_LENGTH IS NULL
OR 
PRODUCT_PHOTO_QTY IS NULL
OR
PRODUCT_WEIGHT_QTY_in_gm IS NULL

;
SELECT * FROM PRODUCT_DATASET;
--CHECKING FOR DUPLICATE VALUES
WITH DUPLICATE_CHECK_7 AS (
							SELECT *,
							ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID,PRODUCT_CATEGORY,PRODUCT_NAME_LENGTH,
							                   PRODUCT_DESCRIPTION_LENGTH,PRODUCT_PHOTO_QTY,PRODUCT_WEIGHT_QTY_in_gm,
											   PRODUCT_LENGTH_in_cm,PRODUCT_HEIGHT_in_cm,PRODUCT_WIDTH_in_cm
											   ORDER BY PRODUCT_ID) AS RNK
							FROM
							PRODUCT_DATASET
)
SELECT * 
FROM DUPLICATE_CHECK_7
WHERE RNK>1;

--NOTE:- THERE ARE NO DUPLICATE ROWS IN THE TABLE
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------

--CREATE TABLE FOR SELLER_DATASET
DROP TABLE IF EXISTS SELLER_DATASET;

CREATE TABLE SELLER_DATASET(
			SELLER_ID VARCHAR(100),
			SELLER_ZIP_CODE INT,
			SELLER_CITY VARCHAR(250),
			SELLER_STATE VARCHAR(10)
);

SELECT * FROM SELLER_DATASET;
--CHECKING FOR NULL VALUES

SELECT COUNT(SELLER_ID),COUNT(SELLER_ZIP_CODE),COUNT(SELLER_STATE) FROM SELLER_DATASET;

--NOTE:- NO NULL VALUES FOUND

--CHECKING FOR DUPLICATE ROWS
WITH DUPLICATE_CHECK_8 AS (
						   SELECT *,
						   ROW_NUMBER() OVER (PARTITION BY SELLER_ID,SELLER_ZIP_CODE,SELLER_CITY,
						   					  SELLER_STATE ORDER BY SELLER_ID) AS RNK
							FROM SELLER_DATASET
)
SELECT * 
FROM 
DUPLICATE_CHECK_8
WHERE RNK>1;
--NOTE:- THERE ARE NO DUPLICATE ROWS IN THE TABLE
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

--CREATE TABLE PRODUCT_CATEGORY_NAME

DROP TABLE IF EXISTS PRODUCT_CATEGORY_NAME;

CREATE TABLE PRODUCT_CATEGORY_NAME(
			PRODUCT_CATEGORY VARCHAR(500),
			PRODUCT_NAME_ENGLISH VARCHAR(500)
);

--CHECKING FOR NULL VALUES

SELECT COUNT(PRODUCT_CATEGORY),COUNT(PRODUCT_NAME_ENGLISH) FROM PRODUCT_CATEGORY_NAME;

--NOTE :- NO NULL VALUES FOUND.

--CHECKING FOR DUPLICATE ROWS

WITH DUPLICATE_CHECK_9 AS (
							SELECT *,
							ROW_NUMBER() OVER (PARTITION BY PRODUCT_CATEGORY,
												PRODUCT_NAME_ENGLISH) AS RNK
							FROM PRODUCT_CATEGORY_NAME
)
SELECT * 
FROM 
DUPLICATE_CHECK_9 
WHERE
RNK>1;

--NOTE:- THERE ARE NO DUPLICATE ROWS AVAILABLE IN THE TABLE.
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------

--******************************************************************************--
--                      DIMENSIONAL MODELING                                     |
--******************************************************************************--


--CREATE DIM_CRM_SELLER

DROP TABLE IF EXISTS DIM_CRM_SELLER;

CREATE TABLE DIM_CRM_SELLER(
			 SELLER_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			 SELLER_ID VARCHAR(100),
			 LOCATION_KEY INT,
			 FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_CRM_LOCATION(LOCATION_KEY)
			 
);

SELECT * FROM DIM_CRM_SELLER;

-----------------------------------------------------------------------------------------
--CREATE DIM_CRM_PRODUCT

DROP TABLE IF EXISTS DIM_CRM_PRODUCT;

CREATE TABLE DIM_CRM_PRODUCT(
			PRODUCT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			PRODUCT_ID VARCHAR(100),
			PRODUCT_CATEGORY_PT VARCHAR(200),
		    PRODUCT_CATEGORY_EN VARCHAR(200),
			PRODUCT_NAME_LENGTH INT,
			PRODUCT_DESCRIPTION_LENGTH INT,
			PRODUCT_PHOTO_QTY INT,
			PRODUCT_WEIGHT_QTY_GM INT,
			PRODUCT_LENGTH_CM INT,
			PRODUCT_HEIGHT_CM INT,
			PRODUCT_WIDTH_CM INT
			
);

SELECT * FROM DIM_CRM_PRODUCT;
------------------------------------------------------------------------------------------
--CREATE DIM_CRM_LOCATION

DROP TABLE IF EXISTS DIM_CRM_LOCATION;

CREATE TABLE DIM_CRM_LOCATION(
			 LOCATION_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			 ZIP_CODE INT NOT NULL UNIQUE,
			 LATITUDE DECIMAL(8,6),
			 LONGITUDE DECIMAL(9,6),
			 CITY VARCHAR(200),
			 STATE VARCHAR(50)
);


SELECT * FROM DIM_CRM_LOCATION;

-------------------------------------------------------------------------------------

--CREATE DIM_CRM_CUSOMERS

DROP TABLE IF EXISTS DIM_CRM_CUSTOMERS;

CREATE TABLE DIM_CRM_CUSTOMERS(
			CUSTOMER_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			CUSTOMER_ID VARCHAR(100),
			CUSTOMER_UNIQUE_ID VARCHAR(100),
			LOCATION_KEY INT,
			FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_CRM_LOCATION(LOCATION_KEY)
								
);

SELECT * FROM DIM_CRM_CUSTOMERS;

------------------------------------------------------------------------------------
--CREATE DIM_CRM_ORDER_DETAILS

DROP TABLE IF EXISTS DIM_CRM_ORDER_DETAILS;

CREATE TABLE DIM_CRM_ORDER_DETAILS(
			 ORDER_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			 ORDER_ID VARCHAR(100),
			 CUSTOMER_ID VARCHAR(100),
			 ORDER_STATUS VARCHAR(50),
			 PURCHASE_DATE TIMESTAMP,
			 APPROVED_DATE TIMESTAMP,
			 SHIPPING_DATE TIMESTAMP,
			 DELIVERY_DATE TIMESTAMP,
			 ESTIMATED_DELIVERY_DATE TIMESTAMP
);


SELECT * FROM DIM_CRM_ORDER_DETAILS;
------------------------------------------------------------------------------------------
---CREATE A DIM_CRM_DATE
DROP TABLE IF EXISTS DIM_CRM_DATE;

CREATE TABLE DIM_CRM_DATE (
    DATE_KEY INT  PRIMARY KEY,
	            
    FULL_DATE DATE NOT NULL,

    DAY INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    QUARTER INT,
    YEAR INT,

    DAY_OF_WEEK INT,                       
    IS_WEEKEND BOOLEAN
);
----------------------------------------------------------------------------------------

--*************************************************************************************---
--                   CREATING A CRM_FACT_TABLE                                            |                 
--*************************************************************************************---

DROP TABLE IF EXISTS CRM_FACT_TABLE;

CREATE TABLE CRM_FACT_TABLE(
    FACT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    DATE_KEY INT NOT NULL,
    CUSTOMER_KEY INT NOT NULL,
    SELLER_KEY INT NOT NULL,
    PRODUCT_KEY INT NOT NULL,
    LOCATION_KEY INT NOT NULL,
    ORDER_KEY INT NOT NULL,

    ORDER_ITEM INT NOT NULL,
    PRICE DECIMAL(10,2),
    FREIGHT_VALUE DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(10,2),

    FOREIGN KEY (DATE_KEY) REFERENCES DIM_CRM_DATE(DATE_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CRM_CUSTOMERS(CUSTOMER_KEY),
    FOREIGN KEY (SELLER_KEY) REFERENCES DIM_CRM_SELLER(SELLER_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_CRM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_CRM_LOCATION(LOCATION_KEY),
    FOREIGN KEY (ORDER_KEY) REFERENCES DIM_CRM_ORDER_DETAILS(ORDER_KEY)
);


SELECT * FROM ORDER_LIST;

SELECT * FROM CRM_FACT_TABLE;


----------------------------------------------------------------------------------------------------------------

--************************************************************************************************--
--                                 POPULATING DIM_TABLES()                                          |
--************************************************************************************************--
--POPULATING DIM_CRM_DATE
INSERT INTO DIM_CRM_DATE (
    DATE_KEY,
    FULL_DATE,
    DAY,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR,
    DAY_OF_WEEK,
    IS_WEEKEND
)

SELECT 
    TO_CHAR(d::DATE, 'YYYYMMDD')::INT AS DATE_KEY,
    d::DATE AS FULL_DATE,

    EXTRACT(DAY FROM d) AS DAY,
    EXTRACT(MONTH FROM d) AS MONTH,
    TO_CHAR(d, 'Month') AS MONTH_NAME,
    EXTRACT(QUARTER FROM d) AS QUARTER,
    EXTRACT(YEAR FROM d) AS YEAR,

    EXTRACT(DOW FROM d) AS DAY_OF_WEEK,

    CASE
        WHEN EXTRACT(DOW FROM d) IN (0,6) THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND

FROM generate_series(
        '2015-01-01'::DATE,
        '2020-12-31'::DATE,
        INTERVAL '1 day'
) d;


SELECT * FROM DIM_CRM_DATE;

---------------------------------------------------------------------------------------------------------------
--POPULATING DIM_CRM_CUSTOMERS
INSERT INTO DIM_CRM_CUSTOMERS(
			CUSTOMER_ID,
			CUSTOMER_UNIQUE_ID,
			LOCATION_KEY
)
SELECT DISTINCT
		C.CUSTOMER_ID,
		C.CUSTOMER_UNIQUE_ID,
		L.LOCATION_KEY
FROM
	
	CUSTOMER_DATA C
JOIN
	DIM_CRM_LOCATION L
ON
	C.CUSTOMER_ZIP_CODE = L.ZIP_CODE;

SELECT * FROM DIM_CRM_CUSTOMERS;


------------------------------------------------------------------------------------------------------------
--POPULATING DIM_CRM_SELLER
INSERT INTO DIM_CRM_SELLER(
			SELLER_ID,
			LOCATION_KEY
)
SELECT DISTINCT
		S.SELLER_ID,
		L.LOCATION_KEY
FROM
	SELLER_DATASET S
JOIN DIM_CRM_LOCATION L
ON
	S.SELLER_ZIP_CODE=L.ZIP_CODE;

SELECT * FROM DIM_CRM_SELLER;

-----------------------------------------------------------------------------------------------------------------
--POPULATING DIM_CRM_PRODUCT
INSERT INTO DIM_CRM_PRODUCT(
			PRODUCT_ID,
			PRODUCT_CATEGORY_PT,
			PRODUCT_CATEGORY_EN,
			PRODUCT_NAME_LENGTH,
			PRODUCT_DESCRIPTION_LENGTH,
			PRODUCT_PHOTO_QTY,
			PRODUCT_WEIGHT_QTY_GM,
			PRODUCT_LENGTH_CM,
			PRODUCT_HEIGHT_CM,
			PRODUCT_WIDTH_CM
			
)
SELECT DISTINCT
		P.PRODUCT_ID,
		P.PRODUCT_CATEGORY,
		PN.PRODUCT_NAME_ENGLISH,
		P.PRODUCT_NAME_LENGTH,
		P.PRODUCT_DESCRIPTION_LENGTH,
		P.PRODUCT_PHOTO_QTY,
		P.PRODUCT_WEIGHT_QTY_IN_GM,
		P.PRODUCT_LENGTH_IN_CM,
		P.PRODUCT_HEIGHT_IN_CM,
		P.PRODUCT_WIDTH_IN_CM
FROM PRODUCT_DATASET P
JOIN
PRODUCT_CATEGORY_NAME PN
ON
P.PRODUCT_CATEGORY=PN.PRODUCT_CATEGORY;
		



SELECT * FROM DIM_CRM_PRODUCT;

--------------------------------------------------------------------------------------------------------------
--POPULATING DIM_CRM_LOCATION
INSERT INTO DIM_CRM_LOCATION(
			ZIP_CODE,
			LATITUDE,
			LONGITUDE,
			CITY,
			STATE
)
SELECT
    GEO_ZIP_CODE,
    AVG(GEO_LATITUDE),
    AVG(GEO_LONGITUDE),
    MIN(GEO_CITY),
    MIN(GEO_STATE)
FROM GEOLOCATION
GROUP BY GEO_ZIP_CODE;



INSERT INTO DIM_CRM_LOCATION (ZIP_CODE, CITY, STATE)
SELECT DISTINCT
    C.CUSTOMER_ZIP_CODE,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE
FROM CUSTOMER_DATA C
LEFT JOIN DIM_CRM_LOCATION L
    ON C.CUSTOMER_ZIP_CODE = L.ZIP_CODE
WHERE L.ZIP_CODE IS NULL;
		

SELECT * FROM DIM_CRM_LOCATION;
-----------------------------------------------------------------------------------------------------------------
-- POPULATING DIM_CRM_ORDER_DETAILS
INSERT INTO DIM_CRM_ORDER_DETAILS (
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    PURCHASE_DATE,
    APPROVED_DATE,
    SHIPPING_DATE,
    DELIVERY_DATE,
    ESTIMATED_DELIVERY_DATE
)
SELECT DISTINCT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    PURCHASE_DATE,
    APPROVED_DATE,
    SHIPPING_DATE,
    DELIVERY_DATE,
    ESTIMATED_DELIVERY_DATE
FROM ORDER_INFO;
-----------------------------------------------------------------------------------------------------------------
--POPULATING  FACT TABLE (CRM_FACT_TABLE)

INSERT INTO CRM_FACT_TABLE (
    DATE_KEY,
    CUSTOMER_KEY,
    SELLER_KEY,
    PRODUCT_KEY,
    LOCATION_KEY,
    ORDER_KEY,
    ORDER_ITEM,
    PRICE,
    FREIGHT_VALUE,
    TOTAL_AMOUNT
)
SELECT
    TO_CHAR(OI.PURCHASE_DATE, 'YYYYMMDD')::INT AS DATE_KEY,

    COALESCE(DC.CUSTOMER_KEY, -1) AS CUSTOMER_KEY,
    COALESCE(DS.SELLER_KEY, -1) AS SELLER_KEY,
    COALESCE(DP.PRODUCT_KEY, -1) AS PRODUCT_KEY,

    COALESCE(DL.LOCATION_KEY, -1) AS LOCATION_KEY,
    DOS.ORDER_KEY,

    OL.ORDER_ITEM,
    OL.PRICE,
    OL.FREIGHT_VALUE,
    (OL.PRICE + OL.FREIGHT_VALUE) AS TOTAL_AMOUNT

FROM ORDER_LIST OL

JOIN ORDER_INFO OI 
    ON OL.ORDER_ID = OI.ORDER_ID   

LEFT JOIN DIM_CRM_CUSTOMERS DC 
    ON OI.CUSTOMER_ID = DC.CUSTOMER_ID

LEFT JOIN DIM_CRM_SELLER DS 
    ON OL.SELLER_ID = DS.SELLER_ID

LEFT JOIN DIM_CRM_PRODUCT DP 
    ON OL.PRODUCT_ID = DP.PRODUCT_ID

LEFT JOIN DIM_CRM_LOCATION DL 
    ON DC.LOCATION_KEY = DL.LOCATION_KEY

JOIN DIM_CRM_ORDER_DETAILS DOS 
    ON OL.ORDER_ID = DOS.ORDER_ID;

	
SELECT * FROM CRM_FACT_TABLE;


INSERT INTO DIM_CRM_PRODUCT OVERRIDING SYSTEM VALUE
VALUES (-1, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN',NULL,NULL,NULL);

INSERT INTO DIM_CRM_SELLER
OVERRIDING SYSTEM VALUE
VALUES (-1, 'UNKNOWN', NULL);

INSERT INTO DIM_CRM_CUSTOMERS
OVERRIDING SYSTEM VALUE
VALUES(-1,'UNKNOWN',NULL,NULL);

INSERT INTO DIM_CRM_LOCATION OVERRIDING SYSTEM VALUE
VALUES(-1,0,0,0,'UNKNOWN','UNKNOWN');

--**********************************************************************************--
--                     PERFORMING THE KPI's           
--**********************************************************************************--
--1). TOTAL REVENUE
SELECT 

COUNT(DISTINCT ORDER_KEY) AS TOTAL_ORDER,
COUNT(DISTINCT CUSTOMER_KEY)AS TOTAL_CUSTOMER,
ROUND(SUM(TOTAL_AMOUNT),2) AS TOTAL_REVENUE,
ROUND(AVG(TOTAL_AMOUNT),2) AS AVG_ORDER_VALUE,
ROUND(SUM(TOTAL_AMOUNT)/COUNT(DISTINCT CUSTOMER_KEY),2) AS REVENUE_PER_CUSTOMER
FROM 
CRM_FACT_TABLE;

--NOTE TOTAL ORDER PLACED--->98666
--     TOTAL CUSTOMERS --->98393 ALMOST 1 ORDER PER CUSTOMER
--     AVG ORDER VALUE ----> 140.64 APPROX PER ORDER
--     AVG EXPENDITURE PER CUSTOMER---> 161.02


--2). TOTAL REVENUE BY YEAR
SELECT D.YEAR AS YEARS,SUM(F.TOTAL_AMOUNT) AS AMOUNT
FROM CRM_FACT_TABLE F
JOIN
DIM_CRM_DATE D 
ON 
F.DATE_KEY=D.DATE_KEY
GROUP BY D.YEAR
ORDER BY D.YEAR
;

SELECT * FROM DIM_CRM_DATE;


--3). HIGHEST MONTHLY REVENUE (TOP 3)
WITH MONTHLY_REVENUE AS (
				SELECT D.YEAR AS YEARS, D.MONTH AS MONTHS,D.MONTH_NAME AS MONTH_NAME,
				ROUND(SUM(F.TOTAL_AMOUNT),2) AS AMOUNT,
				RANK() OVER (PARTITION BY D.YEAR ORDER BY SUM(F.TOTAL_AMOUNT) DESC) AS RANKS 
				FROM CRM_FACT_TABLE F
				JOIN
				DIM_CRM_DATE D
				ON
				F.DATE_KEY=D.DATE_KEY
				GROUP BY D.YEAR,D.MONTH,D.MONTH_NAME
				
)

SELECT YEARS,MONTHS,MONTH_NAME,AMOUNT
FROM MONTHLY_REVENUE
WHERE 
RANKS <4;

--NOTE FOR EVERY YEAR HIGHEST REVENUE WAS GENERATED IN THE LAST QUARTER OF EVERY YEAR

--3). CALCULATE MONTH OVER MONTH GROWTH RATE
WITH MONTHLY_REVENUE AS (
						SELECT
						D.YEAR AS YEARS,
						D.MONTH AS MONTHS,
						D.MONTH_NAME AS MONTH_NAME,
						SUM(F.TOTAL_AMOUNT) AS REVENUE
						FROM
						CRM_FACT_TABLE F
						JOIN
						DIM_CRM_DATE D
						ON
						F.DATE_KEY=D.DATE_KEY
						GROUP BY YEARS,MONTHS,MONTH_NAME
),

MOM_RATE AS (SELECT 
					*,
					LAG(REVENUE)OVER(ORDER BY YEARS,MONTHS) AS PREVIOUS_VALUE
					FROM MONTHLY_REVENUE
					)
SELECT YEARS,MONTHS,MONTH_NAME, REVENUE,
PREVIOUS_VALUE,
ROUND((REVENUE-PREVIOUS_VALUE)/NULLIF(PREVIOUS_VALUE,0) * 100,2) AS MOM_ANALYSIS
FROM
MOM_RATE
ORDER BY YEARS,MONTHS;

--4). NUMBER OF REPEAT CUSTOMERS;
SELECT * FROM CRM_FACT_TABLE;
SELECT * FROM DIM_CRM_CUSTOMERS;
SELECT * FROM DIM_CRM_ORDER_DETAILS;

WITH CUSTOMER_TYPE AS (
    SELECT 
        C.CUSTOMER_UNIQUE_ID,
        COUNT(DISTINCT F.ORDER_KEY) AS TOTAL_ORDERS,
        SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CRM_FACT_TABLE F
    JOIN DIM_CRM_CUSTOMERS C
        ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
    GROUP BY C.CUSTOMER_UNIQUE_ID
)

SELECT 
    CASE 
        WHEN TOTAL_ORDERS > 1 THEN 'Repeat'
        ELSE 'One-Time'
    END AS CUSTOMER_TYPE,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(TOTAL_REVENUE),2) AS AVG_REVENUE
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_TYPE;


--5). PERCENTAGE OF CUSTOMER WHO PLACED MORE THAN 1 ORDER.

WITH CUSTOMER_TYPE AS (
    SELECT 
        C.CUSTOMER_UNIQUE_ID,
        COUNT(DISTINCT F.ORDER_KEY) AS TOTAL_ORDERS,
        SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CRM_FACT_TABLE F
    JOIN DIM_CRM_CUSTOMERS C
        ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
    GROUP BY C.CUSTOMER_UNIQUE_ID
),
CALCULATING_REPEAT_CUSTOMER AS (
					SELECT 
					    CASE 
					        WHEN TOTAL_ORDERS > 1 THEN 'Repeat'
					        ELSE 'One-Time'
					    END AS CUSTOMER_TYPE,
					    COUNT(*) AS CUSTOMER_COUNT,
					    ROUND(AVG(TOTAL_REVENUE),2) AS AVG_REVENUE
					FROM CUSTOMER_TYPE
					GROUP BY CUSTOMER_TYPE
					),
REPEAT_SELECTION AS (
					SELECT *,CUSTOMER_COUNT AS REPEATS
					FROM CALCULATING_REPEAT_CUSTOMER
					WHERE CUSTOMER_TYPE='Repeat'
					
					
)
SELECT R.CUSTOMER_TYPE,ROUND(R.CUSTOMER_COUNT/SUM(C.CUSTOMER_COUNT) * 100,2) AS PERCENTAGE_OF_REPEAT_CUSTOMERS 
FROM CALCULATING_REPEAT_CUSTOMER C
CROSS JOIN
REPEAT_SELECTION R
GROUP BY R.CUSTOMER_TYPE,R.CUSTOMER_COUNT;


--6). WHICH PRODUT CATEGORY GENERATES THE MOST REVENUE


SELECT P.PRODUCT_CATEGORY_PT AS PRODUCTS,SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM 
CRM_FACT_TABLE F
JOIN
DIM_CRM_PRODUCT P
ON
F.PRODUCT_KEY=P.PRODUCT_KEY
JOIN 
DIM_CRM_ORDER_DETAILS O
ON
F.ORDER_KEY=O.ORDER_KEY
WHERE
O.ORDER_STATUS='delivered'
GROUP BY P.PRODUCT_CATEGORY_PT
ORDER BY REVENUE DESC
LIMIT 3;

--NOTE BELEZA_SAUDE GENERATES THE MOST REVENUE OF 1412089.53 FOLLOWED BY RELOGOIS_PRESENTS WITH
--A REVENUE OF 1264333.12 AND THE THIRD BEING CAMA_MESA_BANHO WITH A TOTAL REVENUE OF 1225209.26



--7). WHAT IS THE AVERAGE DELIVERY TIME

SELECT ROUND(AVG(EXTRACT(EPOCH FROM (DELIVERY_DATE - PURCHASE_DATE))/86400),2) AS TIME_TAKEN
FROM DIM_CRM_ORDER_DETAILS
WHERE
ORDER_STATUS='delivered'
AND DELIVERY_DATE IS NOT NULL
;

--NOTE AVG TIME TAKEN 12.56 DAYS

--8). WHICH SELLER GENERATES THE MOST REVENUE



SELECT S.SELLER_ID AS SELLER,SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM CRM_FACT_TABLE F
JOIN
DIM_CRM_SELLER S
ON
F.SELLER_KEY=S.SELLER_KEY
JOIN
DIM_CRM_ORDER_DETAILS O
ON
F.ORDER_KEY=O.ORDER_KEY
WHERE 
O.ORDER_STATUS='delivered'
GROUP BY S.SELLER_ID
ORDER BY REVENUE DESC
LIMIT 3;


--9). WHAT % OF ORDERS ARE CANCELED

SELECT ROUND(
		COUNT(CASE WHEN ORDER_STATUS='canceled'
							THEN 1
							END
			)::DECIMAL /
			 COUNT(*) * 100,2)
			 AS CANCELED_PERCENTAGE
FROM
DIM_CRM_ORDER_DETAILS;

--NOTE APPROXIMATELY 0.63 PERCENT OF THE TOTAL ORDERS PLACED WERE CANCELED


--****************************** RFM MODELING ***********************************
WITH RFM_BASE AS (SELECT
					 C.CUSTOMER_UNIQUE_ID AS UNIQUE_ID,
					 MAX(O.PURCHASE_DATE) AS LAST_PURCHASE_DATE,
					 COUNT(DISTINCT O.ORDER_ID) AS FREQUENCY,
					 COALESCE(SUM(F.TOTAL_AMOUNT),0) AS MONETARY
					 FROM
					 CRM_FACT_TABLE F
					 JOIN
					 DIM_CRM_ORDER_DETAILS O
					 ON
					 F.ORDER_KEY=O.ORDER_KEY
					 JOIN
					 DIM_CRM_CUSTOMERS C
					 ON
					 F.CUSTOMER_KEY=C.CUSTOMER_KEY
					 WHERE
					 O.ORDER_STATUS = 'delivered' and 
					 C.CUSTOMER_UNIQUE_ID IS NOT NULL
					 GROUP BY
					 C.CUSTOMER_UNIQUE_ID
					 
						),
RFM_CALC AS (
    SELECT *,
        EXTRACT(DAY FROM CURRENT_DATE - LAST_PURCHASE_DATE) AS RECENCY
    FROM RFM_BASE
),

RFM_SCORE AS (
    SELECT *,
        NTILE(5) OVER (ORDER BY RECENCY ASC) AS R_SCORE,
        NTILE(5) OVER (ORDER BY FREQUENCY DESC) AS F_SCORE,
        NTILE(5) OVER (ORDER BY MONETARY DESC) AS M_SCORE
    FROM RFM_CALC
)

SELECT *,
CASE 
    WHEN R_SCORE = 5 AND F_SCORE = 5 AND M_SCORE = 5 THEN 'Champions'
    WHEN R_SCORE >= 4 AND F_SCORE >= 4 THEN 'Loyal Customers'
    WHEN R_SCORE >= 4 AND F_SCORE <= 2 THEN 'New Customers'
    WHEN R_SCORE <= 2 AND F_SCORE >= 4 THEN 'At Risk'
    WHEN R_SCORE = 1 AND F_SCORE = 1 THEN 'Lost Customers'
    ELSE 'Potential'
END AS CUSTOMER_SEGMENT
FROM RFM_SCORE;


